reddit:
    client_id: clientid
    client_secret: clientsecret
    username: reddit username
    password: reddit password
    user_agent: Litecoin Tip Bot 1.0
command_list: ['!info', '!help', '!register', '!tip', '!withdraw']
mysql:
    dbUser: user
    dbPassword: pw
    dbName: LiteTest
    dbHost: localhost